### ISSUE TITLE
Translate docs, examples and error messages to english

### ISSUE THREAD

**Issue by VitorLuizC** [shanlh/vue-tinder#1]
Hi, I wanna thank you for this wonderful library and ask for translate docs, examples an error messages to english. Ok, I'm from Brazil and my primary language is portuguese, but english seems to be the common language for open source projects and development.

**Comment by shanlh** [comment]
Okay...I will finish the translation as soon as possible.

**Comment by shanlh** [comment]
Hello, I translated the document into English. 😂Sorry, it’s too late.
