### ISSUE TITLE
Touches stop working after some time

### ISSUE THREAD

**Issue by MaeseppTarvo** [shanlh/vue-tinder#12]
Hey! What can cause a problem where touches work for some time but then suddenly do not anymore? I tried debugging but I can not find a place where it stops working. I found out that both `start` and `move` functions do return values. Just that the card itself won't be affected by the changes.

Does my case go under one of the following descriptions I found from TODO list in README.

1. The mobile end may accidentally touch VueTinder when the finger slides back.
2. In non-sync mode, press and hold the card immediately after the operation. If the front card disappears completely, the DOM node will be stuck after being removed, and the Touchend and Touchcancel events in the component will not be triggered.

For me it seems like it does not have to be completed operation nor in sync mode to reproduce the second item in the list.

These are my parameters on vue-tinder itself:

```
<vue-tinder
      v-if="items.length > 0"
      ref="tinder"
      :allow-super="true"
      key-name="id"
      :pointer-threshold="1.0"
      :super-threshold="1.0"
      :queue.sync="items"
      @submit="submit"
      @update:queue="onListUpdate"
    />
```

Here is illustration about this:

**Comment by CesarGomezTissini** [comment]
Same here.

**Comment by shanlh** [comment]
When I click button fast and frequent, then touch card suddenly, buttons will be stop working and card seems to be frozen.
But if I touch the card again, it will back to normal.
Did you talking about this situation?
I'm hard to find a way that make touches stop working.😅

**Comment by Allwithyou999** [comment]
Yeah, right. And on the Android old version(Galaxy 5), the slider is
crashed. Can you please fix these?
Thanks

**Comment by shanlh** [comment]
I don't have Galaxy, so I used simulator(Android 6.0.1) and repeat above steps, it didn't crashed, only be frozen, if you touch again it will back to normal.

**Comment by shanlh** [comment]
Resolved. #13

**Comment by CesarGomezTissini** [comment]
I was able to reproduce when _re-mock_ cards stack. I mean, in onSubmit method, you call mock method when array length < 3. I did reproduce doing something similar but when array length == 0.
