### ISSUE TITLE
Error loading page

### ISSUE THREAD

**Issue by Alexx23** [shanlh/vue-tinder#17]
Hello.

I have followed the guide published by you (https://shanlh.github.io/vue-tinder/guide/bing-images.html), but when loading the page, the page appears blank with the following error in the console:
http://prntscr.com/uwbry1

Thanks in advance.

**Comment by shanlh** [comment]
Did you set the key for items same as the prop [keyName](https://shanlh.github.io/vue-tinder/api/#keyname)?
