### ISSUE TITLE
Compatibility with VueJS v3.0

### ISSUE THREAD

**Issue by fabrahaingo** [shanlh/vue-tinder#23]
Hi,
I tried installing vue-tinder on my project. However, some attributes seem to have been deprecated in Vue v3 (`slot-scope`, `slot` and `queue.sync`)
I tried updating those on my end, but Vue throws a warning `Unhandled error during execution of scheduler flush`.
Do you have any idea about what might have happened ?

Also, I can't fix a warning triggered by Vetur saying

> Could not find a declaration file for module 'vue-tinder'. '/Users/fabienrahaingomanana/Desktop/citouci/node_modules/vue-tinder/lib/vue-tinder.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/vue-tinder` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-tinder';`

I tried adding a file called `global.d.ts` and running the suggested command. But nothing worked.

**Comment by shanlh** [comment]
The code is updated at branch "next",but I need resolve the build problem.😂
After this I will publish a new version, maybe tomorrow.

**Comment by shanlh** [comment]
I published an alpha version,You can install by `yarn add vue-tinder@alpha` if use vue3.
I haven't write document now, So you can reference this:[https://github.com/shanlh/vue-tinder/blob/next/src/App.vue](https://github.com/shanlh/vue-tinder/blob/next/src/App.vue).
Hope to help you！

**Comment by shanlh** [comment]
Oh I forgot something.
When you import vue-tinder, You need import the style file like `import 'vue-tinder/lib/style.css'` because of vite didn't support build the style into js right now.

**Comment by fabrahaingo** [comment]
Thanks a lot, this worked ! 🤟

**Comment by Duc113311** [comment]
> Tôi đã xuất bản phiên bản alpha, Bạn có thể cài đặt `yarn add vue-tinder@alpha`nếu sử dụng vue3. Hiện tại tôi chưa viết tài liệu, vì vậy bạn có thể tham khảo tài liệu này: https://github.com/shanlh/vue-tinder/blob/next/src/App.vue . Hy vọng sẽ giúp bạn!

T có tham khảo nhưng không thể nào mà quẹt được cũng không báo lỗi 
ae có thể giúp t được ko?

**Comment by Duc113311** [comment]
T đang làm ở bằng Vue 3 nhưng slot-scope, slotvà queue.sync đều khong dùng được t thay thế bằng v-stot, v-bind:queue

**Comment by r0lodex** [comment]
Maybe I'm a little late, but do you plan to make a Nuxt 3 module in Typescript?
