### ISSUE TITLE
请设置vue-tinder的宽高

### ISSUE THREAD

**Issue by FengHaiSheng** [shanlh/vue-tinder#42]
`
<vue-tinder key-name="id" :queue.sync="queue" @submit="fetchMoreNews" style="width: 295px; height: 450px;">
  <template slot-scope="scope">
    <news-item :key="scope.data.id" :detail="scope.data" class="border-none mb-0"></news-item>
  </template>
</vue-tinder>
`

发布到正式站，报错：“请设置vue-tinder的宽高”

**Comment by shanlh** [comment]
我会在 mounted 的时候取 offsetWidth、offsetHeight，看看是不是因为隐藏或其他原因导致没取到
