### ISSUE TITLE
卡片移除回弹插件滑动失效！

### ISSUE THREAD

**Issue by Likeag6xx** [shanlh/vue-tinder#5]
作者，您好！我现在右滑移除卡片之后因为某些判定问题把移除的卡片添加到了数组的第一项之后卡片滑动就失效了，不能滑动，请问这个问题你有解决方法吗？

**Comment by shanlh** [comment]
是移除了又把它放第一张了的意思吗？

**Comment by Likeag6xx** [comment]
是的




------------------ 原始邮件 ------------------
发件人: "单泠浩"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 中午11:05
收件人: "shanlh/vue-tinder"<vue-tinder@noreply.github.com>; 
抄送: "self"<813642290@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shanlh/vue-tinder] 卡片移除回弹插件滑动失效！ (#5)




是移除了又把它放第一张了的意思吗？

**Comment by Likeag6xx** [comment]
因为需要判断是否达到了最大关注数，达到的话就不能再关注了，所以移除去的卡片得回来才行




------------------ 原始邮件 ------------------
发件人: "单泠浩"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 中午11:05
收件人: "shanlh/vue-tinder"<vue-tinder@noreply.github.com>;
抄送: "self"<813642290@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shanlh/vue-tinder] 卡片移除回弹插件滑动失效！ (#5)




是移除了又把它放第一张了的意思吗？

**Comment by shanlh** [comment]
暂时还没这个功能，不过达到最大关注数之后就应该把组件销毁掉显示已经达到最大关注数了。

**Comment by Likeag6xx** [comment]
明白，但是以后希望能在这个插件上看到这个功能，谢谢！！




------------------ 原始邮件 ------------------
发件人: "单泠浩"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 中午11:32
收件人: "shanlh/vue-tinder"<vue-tinder@noreply.github.com>; 
抄送: "self"<813642290@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shanlh/vue-tinder] 卡片移除回弹插件滑动失效！ (#5)




暂时还没这个功能，不过达到最大关注数之后就应该把组件销毁掉显示已经达到最大关注数了。

**Comment by shanlh** [comment]
嗯嗯我在考虑增加这个功能，时间上没这么快，不过你可以按刚才说的做

**Comment by Likeag6xx** [comment]
我会想方案优化这个问题，但还是很谢谢，你的插件帮了我很大的忙。




------------------ 原始邮件 ------------------
发件人: "单泠浩"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 中午11:36
收件人: "shanlh/vue-tinder"<vue-tinder@noreply.github.com>; 
抄送: "self"<813642290@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shanlh/vue-tinder] 卡片移除回弹插件滑动失效！ (#5)




嗯嗯我在考虑增加这个功能，时间上没这么快，不过你可以按刚才说的做

**Comment by shanlh** [comment]
Hi，这个功能加上了～

**Comment by Likeag6xx** [comment]
感谢通知，老哥很强👍


 
---原始邮件---
发件人: "单泠浩"<notifications@github.com&gt;
发送时间: 2019年10月20日 16:09:53
收件人: "shanlh/vue-tinder"<vue-tinder@noreply.github.com&gt;;
抄送: "Likeag6xx"<813642290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [shanlh/vue-tinder] 卡片移除回弹插件滑动失效！ (#5)



Hi，这个功能加上了～
