### ISSUE TITLE
Is it possible to remove the swipe up and swipe down? 

### ISSUE THREAD

**Issue by palomamtnez** [shanlh/vue-tinder#55]
Hello, thanks for this amazing plugin!

I read that there is the possibility to disable the "super like" function, but this doesn't mean that it stops the user to swipe up right? is it possible that it stops doing that? kinda like it bounces back down? and just allows them to swipe left/right

**Comment by shanlh** [comment]
If you set the prop "allow-super" to false, it should be back down when you swipe up.

`<vue-tinder :allow-super="false" />`
