### ISSUE TITLE
Getting this error on replication 请设置vue-tinder的宽高

### ISSUE THREAD

**Issue by rishabhbatra10** [shanlh/vue-tinder#6]
Getting error 请设置vue-tinder的宽高 while all the css variables are set as per the sandbox. Am I missing something ? 
\

**Comment by shanlh** [comment]
Maybe you forgot to set the vue-tinder's width and height, for example:
```
#app .vue-tinder {
  position: absolute;
  z-index: 1;
  left: 0;
  right: 0;
  top: 23px;
  margin: auto;

  width: calc(100% - 20px);
  height: calc(100% - 23px - 65px - 47px - 16px);

  min-width: 300px;
  max-width: 355px;
}
```

**Comment by rishabhbatra10** [comment]
I have added this as you can see in the image attached
<img width="210" alt="Screenshot 2020-03-12 at 6 34 15 PM" src="https://user-images.githubusercontent.com/15319538/76524483-29f1c480-6490-11ea-88b3-f5266cf44dc1.png">

**Comment by rishabhbatra10** [comment]
Just so you I am not using the App.vue component, instead have created a custom component which is being imported in App.vue. Maybe that's what causing the error ?

**Comment by rishabhbatra10** [comment]
Yeah fixed this, We have to specify this 
``` .vue-tinder {
  position: absolute;
  z-index: 1;
  left: 0;
  right: 0;
  top: 23px;
  margin: auto;

  width: calc(100% - 20px);
  height: calc(100% - 23px - 65px - 47px - 16px);

  min-width: 300px;
  max-width: 355px;
} ```
This part in App.vue in order for this to work.

**Comment by shanlh** [comment]
If I can't get the component's width and height, will throw the error, you can remove the "#app", I think the style is not work
