### ISSUE TITLE
可以在uni端使用吗？

### ISSUE THREAD

**Issue by dshuais** [shanlh/vue-tinder#65]
为什么在uniapp端运行不起来

**Comment by dshuais** [comment]
大佬，把插件引入uniapp里面使用，uni不支持插槽以slot-scope="scope"这种形式拿到子组件传的值，只能改成v-slot:name="{data}"类型的。我也改了 也改了您Tider.vue内的代码 为什么接收不到呀。可以指点一下吗？

**Comment by shanlh** [comment]
不清楚，没针对 uniapp 做过兼容😂
