### ISSUE TITLE
使用route-link包裹元素，点击跳转到其他页面，再返回滑动就失效了

### ISSUE THREAD

**Issue by featnet** [shanlh/vue-tinder#7]
![image](https://user-images.githubusercontent.com/23646120/83126435-60dc8b80-a10b-11ea-9757-8ec8c1c9aea8.png)

`<vue-tinder ref="tinder" key-name="key" :queue.sync="recommendList" :offset-y="10" :pointerThreshold="0.2" :superThreshold="0.2" @submit="onClerkStackChange">
                    <router-link slot-scope="{index, status, data}" :to="'/clerk/detail/'+ data.id">
                        <div class="picture" :style="{ 'background-image': `url(${recommendList[index].avatarUrl})` }">
                            <img v-if="data.grade == 2 || data.grade == 3" class="grade" :src="`/static/images/grade_badge_${data.grade}.png`" />
                        </div>
                    </router-link>
</vue-tinder>`

**Comment by shanlh** [comment]
[DEMO](https://codesandbox.io/s/vue-tinder-preview-y1ryv?file=/src/Home.vue)
上面写了个 DEMO，点击返回时没有出现你描述的这个情况

**Comment by featnet** [comment]
`<template>
  <div id="app">
    <navigation>
      <router-view></router-view>
    </navigation>
  </div>
</template>`
之前为了解决跳转后返回还是在原位置，用了vue-navigation这个组件，请问现在有没有其他办法，比如返回的时候，我通过调用方法重新初始化vue-tinder

**Comment by shanlh** [comment]
试试 v-if 或者变换 key，让 vue-tinder 重新挂载下

**Comment by featnet** [comment]
变换key就可以了，谢谢！
